### ISSUE TITLE
SDL2 incompatibility with ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by TyrasNistru** [ppy/SDL2-CS#42]
Hello!

Looks like there is an issue with sdl2 on ubuntu 18.04 LTS. When trying to open the input panel for any controller, it doesn't open, and the log puts out the following error:

```
00:00:43.025 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'SDL_GameControllerHasSensor' in shared library 'SDL2'.
   at SDL2.SDL.SDL_GameControllerHasSensor(IntPtr gamecontroller, SDL_SensorType type)
   at Ryujinx.Input.SDL2.SDL2Gamepad.GetFeaturesFlag() in C:\projects\ryujinx\Ryujinx.Input.SDL2\SDL2Gamepad.cs:line 106
   at Ryujinx.Input.SDL2.SDL2Gamepad..ctor(IntPtr gamepadHandle, String driverId) in C:\projects\ryujinx\Ryujinx.Input.SDL2\SDL2Gamepad.cs:line 90
   at Ryujinx.Input.SDL2.SDL2GamepadDriver.GetGamepad(String id) in C:\projects\ryujinx\Ryujinx.Input.SDL2\SDL2GamepadDriver.cs:line 135
   at Ryujinx.Ui.Windows.ControllerWindow.UpdateInputDeviceList() in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 265
   at Ryujinx.Ui.Windows.ControllerWindow..ctor(MainWindow mainWindow, Builder builder, PlayerIndex controllerId) in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 178
   at Ryujinx.Ui.Windows.SettingsWindow.ConfigureController_Pressed(Object sender, PlayerIndex playerIndex) in C:\projects\ryujinx\Ryujinx\Ui\Windows\SettingsWindow.cs:line 581
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

sdl2 is installed:

```
Package: libsdl2-2.0-0
Version: 2.0.8+dfsg1-1ubuntu1.18.04.4
Priority: optional
Section: universe/libs
Source: libsdl2
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian SDL packages maintainers <pkg-sdl-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1.292 kB
Depends: libasound2 (>= 1.0.27), libc6 (>= 2.27), libpulse0 (>= 0.99.1), libsndio6.1 (>= 1.1.0), libwayland-client0 (>= 1.9.91), libwayland-cursor0 (>= 1.0.2), libwayland-egl1-mesa (>= 10.0.2) | libwayland-egl1, libx11-6 (>= 2:1.2.99.901), libxcursor1 (>> 1.1.2), libxext6, libxi6 (>= 2:1.2.99.4), libxinerama1, libxkbcommon0 (>= 0.5.0), libxrandr2 (>= 2:1.2.99.3), libxss1, libxxf86vm1
Conflicts: libsdl-1.3-0
Replaces: libsdl-1.3-0
Homepage: https://www.libsdl.org/
Task: kubuntu-desktop, kubuntu-full, lubuntu-gtk-desktop, lubuntu-desktop, lubuntu-qt-desktop, ubuntustudio-video, ubuntustudio-graphics, ubuntustudio-audio, ubuntukylin-desktop, ubuntu-budgie-desktop
Supported: 3y
Download-Size: 382 kB
APT-Manual-Installed: yes
APT-Sources: http://br.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
Description: Simple DirectMedia Layer
 SDL é uma biblioteca que permite aos programas acesso de baixo nível
 portável a um framebuffer de vídeo, saída de áudio, mouse e teclado.
 .
 This version of SDL is compiled with X11 and Wayland graphics drivers and
 OSS, ALSA, sndio and PulseAudio sound drivers.
```
Environment:
AMD Ryzen 9 5900X
RTX 3080
32GB RAM 3200Mhz
Kubuntu 18.04 LTS

**Comment by smoogipoo** [comment]
`SDL_GameControllerHasSensor` is only available in SDL2 2.0.14 or later. The contained libs should be used instead of the system-wide ones for greatest compatibility, which I've confirmed do contain the symbol:
```
$ nm -gDC libSDL2.so | grep SDL_GameControllerHasSensor
0000000000044eb0 T SDL_GameControllerHasSensor
```

**Comment by smoogipoo** [comment]
Actually I think this is probably going to be related to us compiling against Ubuntu 20.04 as mentioned in https://github.com/ppy/SDL2-CS/issues/20. Reopening.

**Comment by Thog** [comment]
> 
> 
> Actually I think this is probably going to be related to us compiling against Ubuntu 20.04 as mentioned in #20. Reopening.

It totally is, going to try to provide a fix for that in the next days
